"""empty message

Revision ID: 11725e300341
Revises: 
Create Date: 2025-11-25 08:37:58.276329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11725e300341'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date__load__data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_ldap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sAMAccountName', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('cn', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ldap_cn'), ['cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_sAMAccountName'), ['sAMAccountName'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_ldap_sAMAccountName'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_description'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_cn'))

    op.drop_table('users_ldap')
    op.drop_table('date__load__data')
    # ### end Alembic commands ###
