"""empty message

Revision ID: 223b6dbec904
Revises: 81a507efd000
Create Date: 2025-11-25 14:06:49.341853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223b6dbec904'
down_revision = '81a507efd000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ldap_cn'), ['cn'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_ldap_cn'))

    # ### end Alembic commands ###
