"""empty message

Revision ID: 5c8e79b2084e
Revises: fb1f0dfe135c
Create Date: 2025-11-23 09:43:20.979757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8e79b2084e'
down_revision = 'fb1f0dfe135c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.alter_column('tab_num',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.alter_column('tab_num',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
