"""Add table Tokens

Revision ID: 9e9c490d1229
Revises: 
Create Date: 2025-12-16 21:11:27.465290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e9c490d1229'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('date_load_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(DATETIME(CURRENT_TIMESTAMP, 'localtime'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_ldap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sAMAccountName', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('cn', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ldap_cn'), ['cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_sAMAccountName'), ['sAMAccountName'], unique=False)

    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users_ldap.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token')
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_ldap_sAMAccountName'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_description'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_cn'))

    op.drop_table('users_ldap')
    op.drop_table('date_load_data')
    # ### end Alembic commands ###
