"""empty message

Revision ID: bce3b00f52a0
Revises: 5c8e79b2084e
Create Date: 2025-11-24 15:35:12.881795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce3b00f52a0'
down_revision = '5c8e79b2084e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sAMAccountName', sa.String(length=256), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('cn', sa.String(length=64), nullable=False))
        batch_op.drop_index(batch_op.f('ix_users_ldap_full_name'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_tab_num'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_username'))
        batch_op.create_index(batch_op.f('ix_users_ldap_cn'), ['cn'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_sAMAccountName'), ['sAMAccountName'], unique=False)
        batch_op.drop_column('tab_num')
        batch_op.drop_column('username')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('tab_num', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_ldap_sAMAccountName'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_description'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_cn'))
        batch_op.create_index(batch_op.f('ix_users_ldap_username'), ['username'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_tab_num'), ['tab_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_full_name'), ['full_name'], unique=False)
        batch_op.drop_column('cn')
        batch_op.drop_column('description')
        batch_op.drop_column('sAMAccountName')

    # ### end Alembic commands ###
