"""empty message

Revision ID: fb1f0dfe135c
Revises: 
Create Date: 2025-11-23 09:40:09.961951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb1f0dfe135c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_ldap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('tab_num', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_ldap_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_tab_num'), ['tab_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_ldap_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_ldap', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_ldap_username'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_tab_num'))
        batch_op.drop_index(batch_op.f('ix_users_ldap_full_name'))

    op.drop_table('users_ldap')
    # ### end Alembic commands ###
